name: Continuous integration
on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies & build component library
        run: npm ci
      - name: Run linter
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Build documentation
        run: npm run build:prod
